<?php
declare(strict_types=1); require __DIR__ . '/includes/bootstrap.php'; require_admin();
$playtestPath = __DIR__ . '/downloads/LivingRealms-Playtest-Windows-0.9.21.zip';
$playtestReady = is_file($playtestPath);
$playtestSize = $playtestReady ? number_format((float)filesize($playtestPath) / 1048576, 1) . ' MB' : 'Packaging';
$total = (int)db()->query('SELECT COUNT(*) FROM visitor_events')->fetchColumn();
$todayStmt = db()->prepare('SELECT COUNT(*) FROM visitor_events WHERE visited_at LIKE ?');
$todayStmt->execute([central_now()->format('Y-m-d') . '%']);
$today = (int)$todayStmt->fetchColumn();
$countries = (int)db()->query("SELECT COUNT(DISTINCT country_code) FROM visitor_events WHERE country_code IS NOT NULL")->fetchColumn();
$visits = db()->query('SELECT visited_at,ip_address,city,region,country_code,path,referrer_domain,user_agent,is_bot FROM visitor_events ORDER BY id DESC LIMIT 100')->fetchAll(PDO::FETCH_ASSOC);
$playerAccessEvents = db()->query('SELECT occurred_at,ip_address,email,action,successful FROM player_access_events ORDER BY id DESC LIMIT 100')->fetchAll(PDO::FETCH_ASSOC);
$pageTitle = 'Admin Portal | Living Realms'; require __DIR__ . '/includes/header.php'; ?>
<main class="portal-main"><p class="eyebrow">Administrator</p><h1>Visitor Activity</h1><div class="portal-tabs"><a href="/portal.php">Visitor Activity</a><a href="/portal-signups.php">Player Signups</a><a href="/portal-feedback.php">Bug &amp; Feature Reports</a><a href="#windows-playtest">Windows Playtest</a></div><div class="stats"><div class="panel stat"><strong><?= $total ?></strong>Total requests</div><div class="panel stat"><strong><?= $today ?></strong>Today (Central)</div><div class="panel stat"><strong><?= $countries ?></strong>Countries</div></div>
<section class="panel download-panel" id="windows-playtest"><div><p class="eyebrow">Shared-World Build 0.9.21</p><h2>Windows Playtest</h2><p>Portable 64-bit Windows build connected to the live Living Realms server. Separate accounts share persistent world progress, although players are not yet visible to one another in real time.</p><p class="form-note">Package size: <?= e($playtestSize) ?>. Build 0.9.21 gives settlement workers visible job routes, adds reliable permanent food production, cleans up roads and environmental overlaps, introduces the new gray Stonehaven wall and east gate, and closes the client promptly while safely retrying a pending position save at the next login. Extract the complete ZIP before running LivingRealms.exe and keep every extracted file together.</p></div><div><?php if ($playtestReady): ?><a class="button" href="/playtest-download.php" download>Download Windows Playtest</a><a class="button secondary" href="/playtest/">Open Player Download Page</a><a class="button secondary" href="/portal-feedback.php">Review Player Feedback</a><?php else: ?><span class="button secondary" aria-disabled="true">Build Packaging</span><?php endif; ?></div></section>
<section class="panel"><h2>Player account activity</h2><p class="form-note">Website registration, login, logout, and download events. All times are Central.</p><div class="table-wrap"><table><thead><tr><th>Time (Central)</th><th>Email</th><th>IP</th><th>Action</th><th>Result</th></tr></thead><tbody><?php if (!$playerAccessEvents): ?><tr><td colspan="5">No player access events yet.</td></tr><?php else: ?><?php foreach ($playerAccessEvents as $event): ?><tr><td><?= e($event['occurred_at']) ?></td><td><?= e($event['email'] ?: 'Not signed in') ?></td><td><?= e($event['ip_address']) ?></td><td><?= e(ucwords(str_replace('_', ' ', $event['action']))) ?></td><td><?= $event['successful'] ? 'Successful' : 'Denied' ?></td></tr><?php endforeach; ?><?php endif; ?></tbody></table></div></section>
<section class="panel"><h2>Latest activity</h2><div class="table-wrap"><table><thead><tr><th>Time (Central)</th><th>IP</th><th>Location</th><th>Page</th><th>Referrer</th><th>Type</th></tr></thead><tbody><?php foreach ($visits as $visit): ?><tr><td><?= e($visit['visited_at']) ?></td><td><?= e($visit['ip_address']) ?></td><td><?= e(trim(implode(', ', array_filter([$visit['city'],$visit['region'],$visit['country_code']])))) ?></td><td><?= e($visit['path']) ?></td><td><?= e($visit['referrer_domain'] ?: 'Direct') ?></td><td><?= $visit['is_bot'] ? 'Bot' : 'Visitor' ?></td></tr><?php endforeach; ?></tbody></table></div></section></main>
<?php require __DIR__ . '/includes/footer.php'; ?>
