<?php
declare(strict_types=1); require __DIR__ . '/includes/bootstrap.php'; require_admin();
if ($_SERVER['REQUEST_METHOD']==='POST' && hash_equals(csrf_token(),(string)($_POST['csrf']??''))) {
    $id=(int)($_POST['id']??0); $status=(string)($_POST['status']??'new'); $action=(string)($_POST['action']??'status');
    if ($id>0 && $action==='delete') { $s=db()->prepare('DELETE FROM player_signups WHERE id=?'); $s->execute([$id]); }
    elseif ($id>0 && in_array($status,['new','contacted','invited','declined'],true)) { $s=db()->prepare('UPDATE player_signups SET status=? WHERE id=?'); $s->execute([$status,$id]); }
    header('Location: /portal-signups.php'); exit;
}
$signups=db()->query('SELECT * FROM player_signups ORDER BY id DESC')->fetchAll(PDO::FETCH_ASSOC);
$pageTitle='Player Signups | Living Realms'; require __DIR__ . '/includes/header.php'; ?>
<main class="portal-main"><p class="eyebrow">Administrator</p><h1>Founding Player Signups</h1><div class="portal-tabs"><a href="/portal.php">Visitor Activity</a><a href="/portal-signups.php">Player Signups</a><a href="/portal-feedback.php">Bug &amp; Feature Reports</a></div><div class="panel"><p><strong><?= count($signups) ?></strong> registered player<?= count($signups)===1?'':'s' ?>. Times are Central.</p><div class="table-wrap"><table><thead><tr><th>Signed up</th><th>Email</th><th>Player name</th><th>Play style</th><th>Testing</th><th>Discord</th><th>Status</th><th>Remove</th></tr></thead><tbody><?php foreach($signups as $s): ?><tr><td><?= e($s['created_at']) ?></td><td><a href="mailto:<?= e($s['email']) ?>"><?= e($s['email']) ?></a></td><td><?= e($s['player_name']) ?></td><td><?= e($s['play_style']) ?></td><td><?= e($s['testing_interest']) ?></td><td><?= e($s['discord_name'] ?: '—') ?></td><td><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><select name="status" aria-label="Status for <?= e($s['player_name']) ?>"><?php foreach(['new','contacted','invited','declined'] as $st): ?><option value="<?= $st ?>"<?= $s['status']===$st?' selected':'' ?>><?= ucfirst($st) ?></option><?php endforeach; ?></select><button class="danger-button" type="submit">Save</button></form></td><td><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><input type="hidden" name="action" value="delete"><button class="danger-button" type="submit">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></div></main><?php require __DIR__ . '/includes/footer.php'; ?>
