// <auto-generated />
using System;
using LivingRealms.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LivingRealms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LivingRealmsDbContext))]
    [Migration("20260717125208_Phase4BasicMonstersAndCombat")]
    partial class Phase4BasicMonstersAndCombat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("living_realms")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LivingRealms.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Archetype")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastLogoutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumHealth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<float>("PositionZ")
                        .HasColumnType("real");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique();

                    b.ToTable("Characters", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.CharacterInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("CharacterId", "ItemId")
                        .IsUnique();

                    b.ToTable("CharacterInventory", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Creature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Aggression")
                        .HasColumnType("integer");

                    b.Property<int>("Attack")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Leadership")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumHealth")
                        .HasColumnType("integer");

                    b.Property<float>("MovementSpeed")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<float>("PositionX")
                        .HasColumnType("real");

                    b.Property<float>("PositionY")
                        .HasColumnType("real");

                    b.Property<float>("PositionZ")
                        .HasColumnType("real");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RespawnAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<float>("SpawnX")
                        .HasColumnType("real");

                    b.Property<float>("SpawnY")
                        .HasColumnType("real");

                    b.Property<float>("SpawnZ")
                        .HasColumnType("real");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("RegionId", "FactionId", "Status");

                    b.ToTable("Creatures", "living_realms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8bd3a92f-80a8-46a6-8349-427975490a01"),
                            Aggression = 20,
                            Attack = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Defense = 2,
                            Experience = 0L,
                            Health = 30,
                            LastProcessedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Leadership = 0,
                            Level = 1,
                            MaximumHealth = 30,
                            MovementSpeed = 3.2f,
                            Name = "Brambletail",
                            PositionX = -16f,
                            PositionY = 0.08f,
                            PositionZ = 17f,
                            RegionId = new Guid("7139a553-cea3-45e4-9d91-b3a95629b72e"),
                            Role = "Wild Creature",
                            SpawnX = -16f,
                            SpawnY = 0.08f,
                            SpawnZ = 17f,
                            SpeciesId = new Guid("8ac9948d-3b09-4c70-aaf1-0c36f967c5a1"),
                            Status = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("8bd3a92f-80a8-46a6-8349-427975490a02"),
                            Aggression = 20,
                            Attack = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Defense = 2,
                            Experience = 0L,
                            Health = 30,
                            LastProcessedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Leadership = 0,
                            Level = 1,
                            MaximumHealth = 30,
                            MovementSpeed = 3.2f,
                            Name = "Mosswhisker",
                            PositionX = -8f,
                            PositionY = 0.08f,
                            PositionZ = 34f,
                            RegionId = new Guid("7139a553-cea3-45e4-9d91-b3a95629b72e"),
                            Role = "Wild Creature",
                            SpawnX = -8f,
                            SpawnY = 0.08f,
                            SpawnZ = 34f,
                            SpeciesId = new Guid("8ac9948d-3b09-4c70-aaf1-0c36f967c5a1"),
                            Status = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("8bd3a92f-80a8-46a6-8349-427975490a03"),
                            Aggression = 20,
                            Attack = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Defense = 2,
                            Experience = 0L,
                            Health = 30,
                            LastProcessedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Leadership = 0,
                            Level = 1,
                            MaximumHealth = 30,
                            MovementSpeed = 3.2f,
                            Name = "Thornsnout",
                            PositionX = 12f,
                            PositionY = 0.08f,
                            PositionZ = 32f,
                            RegionId = new Guid("7139a553-cea3-45e4-9d91-b3a95629b72e"),
                            Role = "Wild Creature",
                            SpawnX = 12f,
                            SpawnY = 0.08f,
                            SpawnZ = 32f,
                            SpeciesId = new Guid("8ac9948d-3b09-4c70-aaf1-0c36f967c5a1"),
                            Status = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5d8a9637-a327-4f42-8ec3-a292f548d101"),
                            Aggression = 45,
                            Attack = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Defense = 5,
                            Experience = 0L,
                            Health = 55,
                            LastProcessedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Leadership = 0,
                            Level = 2,
                            MaximumHealth = 55,
                            MovementSpeed = 4.2f,
                            Name = "Ashfang",
                            PositionX = -29f,
                            PositionY = 0.08f,
                            PositionZ = 12f,
                            RegionId = new Guid("7139a553-cea3-45e4-9d91-b3a95629b72e"),
                            Role = "Wild Creature",
                            SpawnX = -29f,
                            SpawnY = 0.08f,
                            SpawnZ = 12f,
                            SpeciesId = new Guid("5ff49fb8-b1db-4a5d-8274-8a0ee8ed4eb2"),
                            Status = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5d8a9637-a327-4f42-8ec3-a292f548d102"),
                            Aggression = 45,
                            Attack = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Defense = 5,
                            Experience = 0L,
                            Health = 55,
                            LastProcessedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Leadership = 0,
                            Level = 2,
                            MaximumHealth = 55,
                            MovementSpeed = 4.2f,
                            Name = "Dusthowl",
                            PositionX = 29f,
                            PositionY = 0.08f,
                            PositionZ = 16f,
                            RegionId = new Guid("7139a553-cea3-45e4-9d91-b3a95629b72e"),
                            Role = "Wild Creature",
                            SpawnX = 29f,
                            SpawnY = 0.08f,
                            SpawnZ = 16f,
                            SpeciesId = new Guid("5ff49fb8-b1db-4a5d-8274-8a0ee8ed4eb2"),
                            Status = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("9230414d-a60d-46ca-9c59-36cc3b867201"),
                            Aggression = 70,
                            Attack = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Defense = 9,
                            Experience = 0L,
                            Health = 90,
                            LastProcessedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Leadership = 0,
                            Level = 5,
                            MaximumHealth = 90,
                            MovementSpeed = 3.6f,
                            Name = "Skrit",
                            PositionX = -23f,
                            PositionY = 0.08f,
                            PositionZ = -39f,
                            RegionId = new Guid("7139a553-cea3-45e4-9d91-b3a95629b72e"),
                            Role = "Wild Creature",
                            SpawnX = -23f,
                            SpawnY = 0.08f,
                            SpawnZ = -39f,
                            SpeciesId = new Guid("5133411d-cb9d-4f00-a16e-ac106d7cfe91"),
                            Status = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("9230414d-a60d-46ca-9c59-36cc3b867202"),
                            Aggression = 70,
                            Attack = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Defense = 9,
                            Experience = 0L,
                            Health = 90,
                            LastProcessedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Leadership = 0,
                            Level = 5,
                            MaximumHealth = 90,
                            MovementSpeed = 3.6f,
                            Name = "Vrak",
                            PositionX = 22f,
                            PositionY = 0.08f,
                            PositionZ = -39f,
                            RegionId = new Guid("7139a553-cea3-45e4-9d91-b3a95629b72e"),
                            Role = "Wild Creature",
                            SpawnX = 22f,
                            SpawnY = 0.08f,
                            SpawnZ = -39f,
                            SpeciesId = new Guid("5133411d-cb9d-4f00-a16e-ac106d7cfe91"),
                            Status = 0,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f4c5a7b9-644f-4c85-b18f-ac38294e3001"),
                            Aggression = 90,
                            Attack = 22,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Defense = 14,
                            Experience = 0L,
                            Health = 180,
                            LastProcessedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Leadership = 0,
                            Level = 8,
                            MaximumHealth = 180,
                            MovementSpeed = 3.2f,
                            Name = "Gorvak",
                            PositionX = 0f,
                            PositionY = 0.08f,
                            PositionZ = -41f,
                            RegionId = new Guid("7139a553-cea3-45e4-9d91-b3a95629b72e"),
                            Role = "Chief",
                            SpawnX = 0f,
                            SpawnY = 0.08f,
                            SpawnZ = -41f,
                            SpeciesId = new Guid("f3260673-96f8-4d56-ad45-25901cae6f98"),
                            Status = 0,
                            Title = "Clan Chief",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.CreatureEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("CreatureId", "Slot")
                        .IsUnique();

                    b.ToTable("CreatureEquipment", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.CreatureSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("SkillKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId", "SkillKey")
                        .IsUnique();

                    b.ToTable("CreatureSkills", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.CreatureSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("AttackRange")
                        .HasColumnType("real");

                    b.Property<int>("BaseAttack")
                        .HasColumnType("integer");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("integer");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("integer");

                    b.Property<float>("BaseMovementSpeed")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<float>("DetectionRadius")
                        .HasColumnType("real");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPersistentByDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("RespawnSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("CreatureSpecies", "living_realms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ac9948d-3b09-4c70-aaf1-0c36f967c5a1"),
                            AttackRange = 1.35f,
                            BaseAttack = 4,
                            BaseDefense = 2,
                            BaseHealth = 30,
                            BaseMovementSpeed = 3.2f,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DetectionRadius = 7f,
                            ExperienceReward = 25,
                            IsPersistentByDefault = true,
                            Key = "forest-rat",
                            Name = "Forest Rat",
                            RespawnSeconds = 45,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5ff49fb8-b1db-4a5d-8274-8a0ee8ed4eb2"),
                            AttackRange = 1.7f,
                            BaseAttack = 10,
                            BaseDefense = 5,
                            BaseHealth = 55,
                            BaseMovementSpeed = 4.2f,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DetectionRadius = 10f,
                            ExperienceReward = 45,
                            IsPersistentByDefault = true,
                            Key = "prairie-wolf",
                            Name = "Prairie Wolf",
                            RespawnSeconds = 75,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("5133411d-cb9d-4f00-a16e-ac106d7cfe91"),
                            AttackRange = 1.8f,
                            BaseAttack = 15,
                            BaseDefense = 9,
                            BaseHealth = 90,
                            BaseMovementSpeed = 3.6f,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DetectionRadius = 12f,
                            ExperienceReward = 90,
                            IsPersistentByDefault = true,
                            Key = "goblin-raider",
                            Name = "Goblin Raider",
                            RespawnSeconds = 120,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("f3260673-96f8-4d56-ad45-25901cae6f98"),
                            AttackRange = 2.1f,
                            BaseAttack = 22,
                            BaseDefense = 14,
                            BaseHealth = 180,
                            BaseMovementSpeed = 3.2f,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DetectionRadius = 15f,
                            ExperienceReward = 220,
                            IsPersistentByDefault = true,
                            Key = "goblin-chief",
                            Name = "Goblin Chief",
                            RespawnSeconds = 300,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Aggression")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DevelopmentStage")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("LastProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaderCreatureId")
                        .HasColumnType("uuid");

                    b.Property<int>("MilitaryStrength")
                        .HasColumnType("integer");

                    b.Property<int>("Morale")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("NextDecisionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<int>("PopulationCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("TechnologyLevel")
                        .HasColumnType("integer");

                    b.Property<int>("TerritorySize")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Factions", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.FactionResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("Capacity")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("FactionId", "Kind")
                        .IsUnique();

                    b.ToTable("FactionResources", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.FactionStructure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("StructureType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.ToTable("FactionStructures", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BaseValue")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Items", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.PlayerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DisconnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasFilter("\"TokenHash\" IS NOT NULL");

                    b.HasIndex("AccountId", "DisconnectedAt");

                    b.ToTable("PlayerSessions", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ThreatLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Regions", "living_realms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7139a553-cea3-45e4-9d91-b3a95629b72e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The first playable valley of Living Realms.",
                            Key = "stonehaven-valley",
                            Name = "Stonehaven Valley",
                            ThreatLevel = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.ScheduledEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("\"IdempotencyKey\" IS NOT NULL");

                    b.HasIndex("Status", "ScheduledAt");

                    b.ToTable("ScheduledEvents", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DefenseRating")
                        .HasColumnType("integer");

                    b.Property<int>("Food")
                        .HasColumnType("integer");

                    b.Property<int>("GuardStrength")
                        .HasColumnType("integer");

                    b.Property<int>("Iron")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAttackedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stone")
                        .HasColumnType("integer");

                    b.Property<int>("StructuralIntegrity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Wood")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "Name")
                        .IsUnique();

                    b.ToTable("Settlements", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.WorldHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("CreatureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ImportanceLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("RegionId", "OccurredAt");

                    b.ToTable("WorldHistory", "living_realms");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Character", b =>
                {
                    b.HasOne("LivingRealms.Domain.Entities.Account", "Account")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivingRealms.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.CharacterInventory", b =>
                {
                    b.HasOne("LivingRealms.Domain.Entities.Character", "Character")
                        .WithMany("Inventory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivingRealms.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Creature", b =>
                {
                    b.HasOne("LivingRealms.Domain.Entities.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LivingRealms.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LivingRealms.Domain.Entities.CreatureSpecies", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Region");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.CreatureEquipment", b =>
                {
                    b.HasOne("LivingRealms.Domain.Entities.Creature", "Creature")
                        .WithMany("Equipment")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LivingRealms.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.CreatureSkill", b =>
                {
                    b.HasOne("LivingRealms.Domain.Entities.Creature", "Creature")
                        .WithMany("Skills")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.FactionResource", b =>
                {
                    b.HasOne("LivingRealms.Domain.Entities.Faction", "Faction")
                        .WithMany("Resources")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.FactionStructure", b =>
                {
                    b.HasOne("LivingRealms.Domain.Entities.Faction", "Faction")
                        .WithMany("Structures")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.PlayerSession", b =>
                {
                    b.HasOne("LivingRealms.Domain.Entities.Account", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Settlement", b =>
                {
                    b.HasOne("LivingRealms.Domain.Entities.Region", "Region")
                        .WithMany("Settlements")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Account", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Character", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Creature", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Faction", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("Structures");
                });

            modelBuilder.Entity("LivingRealms.Domain.Entities.Region", b =>
                {
                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
