<?php
return [
 'features' => [
  ['A Living World','Forests spread. Roads become dangerous. Mines are claimed. Villages grow into towns—or disappear entirely.'],
  ['Enemies That Remember','The creature that escapes today may return stronger tomorrow, carrying new scars, skills, equipment, and hatred.'],
  ['Civilizations Beyond Humanity','Goblins gather resources, build defenses, promote leaders, raid settlements, and form powers of their own.'],
  ['History Created by Players','Every victory, defeat, betrayal, siege, and sacrifice can become part of the permanent history of the realm.'],
 ],
 'folklore' => [
  ['The Wolf Who Learned the Bell','Stonehaven Valley',['Long ago, the wolves of Stonehaven feared the chapel bell. Whenever it rang, hunters gathered and drove them back into the forest.','One winter, an old gray wolf began watching from the tree line. It learned that the bell did not summon hunters by magic. It summoned them because men heard it.','The wolf waited for a storm. When the wind buried the sound, the pack entered the village unseen.','Since then, the people of Stonehaven say that beasts do not remain beasts forever. Anything that survives long enough will eventually learn.']],
  ['Never Leave a Small Fire Burning','Northern Road',['Travelers along the northern road are taught to extinguish every flame before they sleep. Not because of forest fires. Because goblin scouts search for smoke.','A single cooking fire once led the Darkwood Clan to a merchant camp. The merchants escaped, but the goblins found their maps, tools, and iron. A year later, the same goblins controlled the road.','The old warning remains: Never leave a small fire burning. Small things have a way of becoming kingdoms.']],
  ['The Empty Chair','Stonehaven',['Every tavern in Stonehaven keeps one chair empty during the first winter moon.','The chair belongs to Captain Rowan Hale, who left with forty guards to destroy a young monster nesting beneath the ruined watchtower. The creature was believed to be weak. None returned.','Years later, travelers claimed they saw the same beast wearing pieces of the captain’s armor. No one knows whether Rowan died beneath the tower. The chair remains empty in case he returns.']],
  ['The Road That Changed Its Name','Eastern Trade Road',['The eastern trade road once carried grain, iron, and silk between three prosperous settlements. Then the raids began.','At first, merchants called it the Darkwood Road. After the first caravan vanished, they called it the Broken Road. After the second settlement fell, they called it Widow’s Way.','No road changes its name without blood.']],
  ['The King Beneath the Hill','Greenhill',['Children are warned never to knock three times on the stones beneath Greenhill.','The old stories say a king sleeps below them with an army that never rotted. Some believe he was human. Others believe he was the first goblin to wear a crown.','The hill has remained silent for centuries. Last spring, shepherds reported hearing hammers beneath the earth.']],
 ],
 'legends' => [
  ['The Ash Crown','Before the northern kingdoms were divided, a warlord named Varrek united seven tribes beneath a crown forged from black iron and burned bone. Varrek was not born powerful. He survived, learned, defeated stronger rivals, and took what they carried. By the time the kingdoms recognized the danger, he commanded an empire. The Ash Crown vanished when he fell. Some believe it waits for another survivor worthy of wearing it.'],
  ['The Last Stand of Stonehaven','The prophecy does not say Stonehaven will fall. It says the bells will ring until no hand remains to pull the rope. It says the fields will burn and the northern road will disappear beneath the feet of an army. Yet the final line has never been translated the same way twice: “Stonehaven shall perish,” or “Stonehaven shall be remembered.”'],
  ['The Nameless Wolf','Hunters tell of a wolf that has lived longer than any natural beast. Its fur has turned white with age, its body carries broken arrows from forgotten battles, and lesser wolves follow wherever it walks. The people refuse to name it, fearing it belongs to something older.'],
  ['The City the Forest Swallowed','West of the old river lies a forest too dense for sunlight. Beneath its roots are streets, homes, and doors no scholar has opened. The city was abandoned after every road leading outward vanished beneath the trees. At night, bells can still be heard beneath the roots.'],
  ['The First Chronicle','The oldest known book in the realm contains no beginning. Its first surviving page describes a battle already underway. Its final page is blank. The monks who guarded it believed the book recorded history as it happened. When their monastery burned, the Chronicle disappeared.'],
 ],
 'rumors' => ['A goblin wearing a knight’s helmet has been seen near the northern road.','The wolves no longer flee when the chapel bell rings.','Smoke rises from the ruined watchtower every third night.','Three merchants entered Darkwood this week. Only their horses returned.','A farmer swears the goblins have begun planting crops.','The old chief is dead. Something younger now commands the camp.','Someone repaired the bridge near Widow’s Way. No human settlement claims responsibility.','The forest moved closer to Stonehaven during the night.'],
 'creatures' => [
  ['Goblin Raider','Scavenger → Goblin Raider → Goblin Veteran → Goblin Captain → Goblin Chieftain → Goblin Warlord','A goblin is rarely dangerous because of what it is. It is dangerous because of what it may become.'],
  ['Prairie Wolf','Young Wolf → Prairie Wolf → Pack Hunter → Alpha Wolf → Dire Alpha → Legendary Beast','Every scar means it survived something meant to kill it.'],
  ['Bandit Scout','Thief → Scout → Raider → Bandit Captain → Outlaw Lord','Bandits who survive long enough stop stealing from kingdoms and begin founding their own.'],
  ['Skeleton Warrior','Restless Dead → Skeleton Warrior → Crypt Guardian → Death Knight → Undying Commander','The dead do not grow tired. Some remember enough to grow stronger.'],
 ],
 'chronicles' => [['Day 3','The Darkwood Clan established its first permanent camp.'],['Day 8','A wolf known as Gray-Ear survived an encounter with three travelers.'],['Day 14','Stonehaven lost two farms to raiders.'],['Day 19','Grik was declared Chieftain of the Darkwood Clan.'],['Day 27','Players reclaimed the northern watchtower.'],['Day 31','Gray-Ear formed a pack and killed the hunter who wounded him.'],['Day 45','The goblins captured the abandoned iron mine.'],['Day 52','The first siege of Stonehaven began.']],
];
